### ISSUE TITLE
Tests fail to build under go 1.15

### ISSUE THREAD

**Issue by risicle** [cloudfoundry/credhub-cli#106]
Attempting to run tests for 2.9.0 under go 1.15 on ~linux~ macos 10.14 gives me:

```
config/config_test.go:107:54: conversion from Duration (int64) to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

where it builds & runs happily on go 1.14.

**Comment by peterhaochen47** [comment]
Cannot reproduce with `go version go1.15.15 darwin/amd64`. Maybe they have fixed this issue. In any case, we have scheduled work to make the CLI build in golang 17.
