### ISSUE TITLE
credhub-cli arm64 / aarch64 release

### ISSUE THREAD

**Issue by td03sap** [cloudfoundry/credhub-cli#112]
Hello, 

Can you please make a release for Linux arm64 / aarch64 ?

Regards,
T.

**Comment by LeePorte** [comment]
I'd also suggest adding a Darwin arm64 release with the rise of M1 silicon.

**Comment by hsinn0** [comment]
pivotaltracker #182787669

**Comment by dennisjbell** [comment]
Any update on this, or the ability to build it directly instead of relying on a package manager?

**Comment by hsinn0** [comment]
@dennisjbell, we have not started working on this issue yet.  Meanwhile, can you clone https://github.com/cloudfoundry/credhub-cli to build from source?

**Comment by joshuaauger** [comment]
I'm surprised this still doesn't exist. Are there any updates on Arm64/Aarch64 support?

**Comment by hsinn0** [comment]
We have not prioritized this yet, partly because of the existence of the workaround, i.e. building from source.  We will plan to prioritize this during our next iteration planning.

**Comment by tcdowney** [comment]
@hsinn0 any update?

**Comment by peterhaochen47** [comment]
We will discuss the priority of this request at our next planning meeting.

**Comment by bruce-ricard** [comment]
[Done](https://github.com/cloudfoundry/credhub-cli/releases/tag/2.9.21)

The new version should also be available through `brew` very soon. (I don't know how long changes to the tap take to propagate).
