### ISSUE TITLE
brew install cloudfoundry/tap/credhub-cli is failing due to missing arch section

### ISSUE THREAD

**Issue by sbogar-shs** [cloudfoundry/credhub-cli#118]
What version of the credhub server you are using?

What version of the credhub cli you are using?
2.9.22

If you were attempting to accomplish a task, what was it you were attempting to do?
brew install cloudfoundry/tap/credhub-cli is currently failing on version 2.9.22 due to a missing arch entry in the file name.

What did you expect to happen?
It should have grabbed the correct file for the architecture I am on:
credhub-linux-amd64-2.9.22.tgz 
This file DOES exist and can be downloaded

What was the actual behavior?
Fetching cloudfoundry/tap/credhub-cli
Downloading https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.22/credhub-linux-2.9.22.tgz
curl: (22) The requested URL returned error: 404
Error: credhub-cli: Failed to download resource "credhub-cli"
Download failed: https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.22/credhub-linux-2.9.22.tgz

The file 
credhub-linux-2.9.22.tgz 

Does NOT exist and cannot be downloaded due to a 404 error.

Please confirm where necessary:
* [X ] I have included a log output
* [ X] My log includes an error message
* [ X] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/) 
I will also crack a ticket with VMWare support

**Comment by sbogar-shs** [comment]
I have been able to replicate the issue again using the following steps:

[bug-replication-terminal-session.txt](https://github.com/cloudfoundry/credhub-cli/files/13297575/bug-replication-terminal-session.txt)

**Comment by hsinn0** [comment]
Thanks for reporting. We will take a look at it.

**Comment by peterhaochen47** [comment]
@sbogar-shs Thanks! Should be fixed now, please try again. 
The fix: https://github.com/cloudfoundry/homebrew-tap/commit/57e380fcbed9860a0b89d4ba9a97b3bf353ba90e
