### ISSUE TITLE
Windows cli error on interactive JSON

### ISSUE THREAD

**Issue by Salamandastron1** [cloudfoundry/credhub-cli#87]
What version of the credhub server you are using?
Server Version: 2.5.9

What version of the credhub cli you are using?
CLI Version: 2.6.2

If you were attempting to accomplish a task, what was it you were attempting to do?
store multiple secrets on the credhub server

What did you expect to happen?
expected the secrets to be stored

What was the actual behavior?
error in interactive mode, 
```
$ credhub set -n test -t json -v '{"abc": "true"}'
'{"abc": "true"}' and the error "a" is not  recognized expected object start
```

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ x] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by mxplusb** [comment]
@Salamandastron1 are you use `cmd.exe` or `powershell.exe`?

**Comment by Salamandastron1** [comment]
Unclear let me get this info for you tomorrow

**Comment by jtarchie** [comment]
based on the example, I bet this was in git-windows `bosh` emulation

**Comment by hsinn0** [comment]
Closing old inactive issues.
